### ISSUE TITLE
Bienvenue sur le suivi de projet GitHub

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#1]
=> ETQ (En Tant Que) Contributeurice du projet je sais comment fonctionne le dépôt

Bonjour et bienvenue sur notre outil de suivi de projet.

_Si vous lisez ce message depuis vos emails, merci de cliquer sur le lien en bas "View it on GitHub" ou "Lire sur GitHub"._

Ce site web est l'outil de développement GitHub. Il nous permet de versionner notre code (conserver l'historique des modifications) et de communiquer sur les fonctionnalités en cours de développement.

Le message que vous lisez actuellement est un ticket de suivi (aussi appelé "issue"). C'est sous ce format que nous listons toutes les fonctionnalités demandées et bugs divisés en unités de développement. C'est aussi sous ce format que la totalité de nos échanges devront être stockés. Nous évitons les Emails pour conserver l'historique des échanges, rangés dans les tickets dédiés, pour ne rien perdre de vos besoins et demandes.

Au cours du développement, nous vous demanderons de :

- **répondre à nos points de blocage**. Pour cela, comme pour le présent ticket, vous serez notifiés par un Email qui contient un lien pour venir sur l'interface. Nous vous donnerons le plus d'informations possibles sur le problème. Pour nous répondre, vous pouvez écrire un message dans la partie dédiée ci-dessous, quand vous avez le temps de le faire. *Nous vous demandons d'ailleurs de bien vouloir écrire un message dès à présent et de le valider. Merci.*
- **suivre l'avancement du projet** dans le Kanban dédié. Ce Kanban se trouve à l'adresse suivante que vous pouvez ouvrir dès à présent dans un nouvel onglet : <https://github.com/spyrales/shinygouv/projects/1>
    + Vous verrez que le ticket que vous êtes en train de lire se trouve dans la colonne *"Bloqué"*. Cette colonne de tickets vous est adressée. Tous les tickets qui s'y trouvent nécessitent des informations complémentaires pour être traités. En théorie, vous aurez reçu un email pour chacun d'entre eux, mais s'il y en a trop, vous savez maintenant où les retrouver.
- **valider les tickets terminés**. Dans le Kanban, vous avez une colonne en fin de Kanban nommée *A valider*. Il s'agit des tickets que nous considérons avoir implémentés et qui nécessitent validation de votre part.
  + Lorsque vous pouvez faire la validation sans assistance de notre part, nous vous donnerons toutes les instructions pour savoir comment valider. Vous pourrez écrire un message du type : "Je valide la fermeture de ce ticket."
  + En cas de ticket plus complexe ou plus technique, nous le validerons ensemble lors d'un point d'avancement en direct. Auquel cas, nous validerons la fermeture dans le compte-rendu de réunion.

Notez que nos échanges lors de réunions en direct seront rédigés et accessibles pour vous dans :

- [x] Le Wiki de ce projet : <https://github.com/spyrales/shinygouv/wiki>
- La vision générale des livrables: https://github.com/spyrales/shinygouv/wiki/Key_Dates

Merci de bien vouloir nous indiquer que vous avez lu et approuvé à la date d'aujourd'hui ce mode de fonctionnement en écrivant : "lu et approuvé, le {date du jour}" (Mettre la date du jour) dans un message ci-dessous (Emplacement "Write" ou "Ecrire") et valider l'envoi du message en cliquant sur le bouton vert "Comment" ou "Envoyer".
Suite à quoi, nous nous chargerons de fermer ce ticket.

**Comment by statnmap** [comment]
J'ajoute une information complémentaire: 

## Comment valider les tickets ?

La validation se fait par les commanditaires, sur les tickets ajoutés à la colonne "Validation" du Projet: https://github.com/spyrales/shinygouv/projects/1  
Vous verrez dans nos tickets qu'il y a au moins trois parties:

- ETQ (En tant que)
- Critères de validation
- Comment technique

Ces parties s'adressent en premier aux développeureuses pour savoir quoi et comment traiter le besoin.  
Lors de la validation, vous verrez la partie "Critères de validation" évoluer avec les consignes ou les captures d'écran qui vous permettent de valider le ticket. Nous vous demandons: 

- De cocher les cases de chacun de ces critères si vous les valider
-  D'ajouter un message dans le fil des commenaitres de l'issue pour nous indiquer si vous le validez complètement, ou s'il y a des corrections à apporter.

Ensuite, nous nous occupons de fermer le ticket et de ré-ouvrir tous ceux qui seraient nécessaires.  

C'est à vous !

**Comment by franck-gaspard** [comment]
lu et approuvé le 18/07/2022

**Comment by jdlom** [comment]
lu et approuvé le 10/08/2022
