### ISSUE TITLE
Amélioration header : pouvoir mettre l'intitulé sur 3 lignes ou plus

### ISSUE THREAD

**Issue by jdlom** [spyrales/shinygouv#104]
Bonjour,
pour le moment le header ne permet d'afficher l'intitulé que sur 2 lignes. Néanmoins beaucoup de site d'administration sont sur au moins 3 lignes.
https://www.normandie.developpement-durable.gouv.fr/
https://www.enseignementsup-recherche.gouv.fr/fr

Je suggère qu'on supprime l'argument `officiel` et qu'on accepte que l'`intitule` soit de type `shiny.tag`

On pourrait dans un premier temps avoir ceci :
```r
shinygouv::fluidPage_dsfr(
  header = shinygouv::header_dsfr(
    intitule = span("Préfet", br(), "de la région", br(), "Normandie"),
  )
) %>% 
  html_print()
```
Qu'en pensez-vous ?

## Validation

- [x] L'argument `officiel` a été supprimé

![image](https://github.com/spyrales/shinygouv/assets/49268931/22d17805-4fea-45b1-b1e3-f9731dc9e86e)

- [x] On peut passer un header sur 3 lignes via un span

![image](https://github.com/spyrales/shinygouv/assets/49268931/951e5178-768a-47a2-a14f-d3dff24b40f2)

![image](https://github.com/spyrales/shinygouv/assets/49268931/020de648-7200-4d96-9168-a376ce0fc00d)

**Comment by jdlom** [comment]
@ymansiaux 👍🏻

**Comment by jengelaere** [comment]
Je vois pour rendre ça plus R friendly, le span et le br ne parlent pas à tous. On va avoir des utilisateurs qui font leur première shiny avec shinygouv
