### ISSUE TITLE
[composant] Implémentation de [radioGroupButtons]

### ISSUE THREAD

**Issue by ymansiaux** [spyrales/shinygouv#105]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `[radioGroupButtons]()` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [x] Une fonction implementée, documentée, testée : `[radioGroupButtons]_dsfr()'

   - [ ] Avec la documentation dans le corps de la fonction

![image](https://github.com/spyrales/shinygouv/assets/49268931/dc6024a2-4649-48b4-9e22-5df406a3082c)

   - [x] Des tests unitaires

![image](https://github.com/spyrales/shinygouv/assets/49268931/80d9f137-23b1-4901-95ca-a6d0238f4a8f)

  
- [x] Un exemple d'utilisation dans l'application de démonstration est disponible

https://ssm-ecologie.shinyapps.io/shinygouv-demo/#inputs_a_choix_limites

## Comment technique

- Je crée une branche pour développer la fonctionnalité
- Utilisation du workflow décrit dans  'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Utiliser le flat file fourni pour développer avec {fusen}
- J'ouvre une PR assignée aux responsables de projet lorsque c'est traité

**Comment by jengelaere** [comment]
👌
