### ISSUE TITLE
[fix] Renommer l'app de démo dans inst

### ISSUE THREAD

**Issue by Cervangirard** [spyrales/shinygouv#113]
Critère de succès

- [x] L'app , précédemment appelée "appshinydemo" est renommé par test.convert.dsfr

![image](https://github.com/spyrales/shinygouv/assets/38312934/fd246f3b-fb89-4fac-a1d2-d0b5a509836e)

- [x] Il n'y a plus de "appshinydemo" dans shinygouv

![image](https://github.com/spyrales/shinygouv/assets/38312934/3910c90e-4e40-405e-8be3-a6de8e712279)

**Comment by jengelaere** [comment]
👌
