### ISSUE TITLE
[fix] Update RadioGroupButtons

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#115]
L'update du composant `RadioGroupButtons` ne fonctionne pas correctement (voir exemple sur l'application de demo)

# Validation

- [x] L'update du "radioGroupButton" est fonctionnel

![Animation](https://github.com/spyrales/shinygouv/assets/49268931/e159161e-7e9f-4bf3-a97b-8e4fb5ef91ef)

# Dev

**Comment by jengelaere** [comment]
👌
