### ISSUE TITLE
[fix] Resoudre convert_to_dsfr

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#116]
Critère de succès

- [x] L'utilisateur est informé que l'utilisation du tabPanel dans une navbarPage doit être remplacé par un `navbarPanel_dsfr` dans un `navbarPage_dsfr`
- [x] l'utilisateur est informé qu'il doit rajouter un header dans le navbarPage_dsfr

![image](https://github.com/spyrales/shinygouv/assets/38312934/1f6c2f39-32aa-4ef0-91ca-2a9c52b2ed5b)

- [x] La fonction `convert_to_dsfr()` a le badge 'Experimental`

![image](https://github.com/spyrales/shinygouv/assets/38312934/c16fb6dd-3673-430d-9da2-845742be5ba8)

Technique

**Comment by jengelaere** [comment]
👌
