### ISSUE TITLE
[chore] Refactoring app_ui and app server

### ISSUE THREAD

**Issue by Cervangirard** [spyrales/shinygouv#118]
## Validation

- [x] L'appli présente les différents composants en fonction de leur type
- [x] L'ensemble des composants et leurs options de mise à jour sont fonctionnelles

https://ssm-ecologie.shinyapps.io/shinygouv-demo/

## Dev

- [ ] Basculer en modules app_ui et app_server

**Comment by jengelaere** [comment]
C'est bcp plus lisible qu'avant 👏
