### ISSUE TITLE
[composant] Implémentation de [dateRangeInput_dsfr]

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#128]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `dateRangeInput()` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [x] Une fonction implementée, documentée, testée : `dateRangeInput]_dsfr()'
   - [x] Avec la documentation dans le corps de la fonction
![image](https://github.com/spyrales/shinygouv/assets/38312934/eba4dad4-0dd0-4789-9684-c19775019af5)

   - [x] Des tests unitaires

![image](https://github.com/spyrales/shinygouv/assets/38312934/2255b24f-1213-4abb-bd1f-2148eadb660c)

- [x] Un exemple d'utilisation dans l'application de démonstration est disponible

https://ssm-ecologie.shinyapps.io/shinygouv-demo/#inputs_a_choix_limites

## Comment technique

- Je crée une branche pour développer la fonctionnalité
- Utilisation du workflow décrit dans  'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Utiliser le flat file fourni pour développer avec {fusen}
- J'ouvre une PR assignée aux responsables de projet lorsque c'est traité

**Comment by MurielleDelmotte** [comment]
Point sur l'avancement , le `dateRangeInput_dsfr()` est fonctionnel mais il reste à régler certains points:
- Au lancement d'un application, l'input est à NULL tant qu'une des dates n'a pas été modifiée
  - Essai réalisé via un session$sendCustomMessage
- Restera l'update à implémenter

**Comment by jengelaere** [comment]
👌
