### ISSUE TITLE
[documentation] Vérification périodique: Quelle licence utiliser ?

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#13]
ETQ dev, je souhaite connaitre sous quel régime de licence le projet doit-il etre développé

## Problème

Pour le moment, nous avons choisi de mettre la même licence que pour {gouvdown}: https://github.com/spyrales/shinygouv/blob/main/LICENSE  

- [ ] Était-ce le choix adapté ?

**Comment by jengelaere** [comment]
ça me parait très bien pour démarrer, mais il faudra peut être vérifier au fur et à mesure sa compatibilité avec les licences des packages qu'on va utiliser ? 
https://joinup.ec.europa.eu/collection/eupl/solution/joinup-licensing-assistant/jla-find-and-compare-software-licenses

**Comment by statnmap** [comment]
C'est noté, merci.  Je met ce ticket dans la colonne "Open", on le reprendra plus tard au cours du développement si besoin.

**Comment by ColinFay** [comment]
Ok, vu avec Juliette
