### ISSUE TITLE
[fix] Typo dans le nom de la classe `fr-container-fluid`

### ISSUE THREAD

**Issue by ArthurData** [spyrales/shinygouv#136]
## Validation

- [x] Au sein du fichier `inst/v1.9.3/composant/fluidpage.html`, le nom de la classe est corrigée afin d'obtenir `fr-container--fluid`

![image](https://github.com/spyrales/shinygouv/assets/38312934/c93859bb-8848-4317-adcc-1a1197445f6b)

https://github.com/spyrales/shinygouv/blob/main/inst/v1.9.3/composant/fluidpage.html

## Technique 

Code proposé par le DSFR:

```
<div class="fr-container--fluid">  
  <div class="fr-grid-row">    
    <div class="fr-col"></div>    
    <div class="fr-col-4"></div>    
    <div class="fr-col-12 fr-col-lg-4"></div>  
  </div>
</div>
```

**Comment by MurielleDelmotte** [comment]
validé
