### ISSUE TITLE
[documentation] Quelle(s) langue(s) utiliser pour la documentation ?

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#15]
ETQ dev, nous avons besoin de savoir dans quelle langue documenter le package

## Critères de validation

- [x] L'information sur la langue est passée auprès des dev
![image](https://user-images.githubusercontent.com/21193866/179719779-de2668d4-e18d-49dd-ba1f-8f872628bd1d.png)
- [x] Les dev ont mis à jour leurs templates de commit
![image](https://user-images.githubusercontent.com/37626302/179737995-b3e5407f-e9c4-4b0d-98bd-75867649435c.png)
- [x] La documentation pour les développeureuses informe des langues à utiliser: https://github.com/spyrales/shinygouv/tree/15_francisation/dev/documentation
![image](https://user-images.githubusercontent.com/21193866/179726055-2bc9eb5f-4ac1-433b-b263-2f1a3ac35c7a.png)
- [x] Le template de commit par défaut est en français: https://github.com/spyrales/shinygouv/blob/15_francisation/.github/template_commit
![image](https://user-images.githubusercontent.com/21193866/179726153-61ca8df1-a1d0-469b-8534-547ae7ed50b8.png)
- [x] Le template de Pull request par défaut est en français: https://github.com/spyrales/shinygouv/blob/15_francisation/.github/pull_request_template.md
![image](https://user-images.githubusercontent.com/21193866/179726278-5c49471c-9692-4b5d-9cf2-ac1a7a01cd18.png)

- [x] Le guide de Contribution est en anglais et dirige vers la documentation des développeureuses: https://github.com/spyrales/shinygouv/blob/15_francisation/.github/CONTRIBUTING.md
![image](https://user-images.githubusercontent.com/21193866/179726523-7e3e4757-c1e2-4951-b98b-d54e86c7983f.png)

## Problèmes à résoudre

Le package contient plusieurs sources de documentation. Pour certaines, la rédaction en français nécessite des ajustements liés à l'encodage et à l'utilisation des caractères ASCII.   
Pourriez-vous nous indiquer, pour chacune des sources de documentation suivantes, quelle langue utiliser ?  

- [x] Rapports d'exploration (présentés en vignettes) : Français
- [x] Vignettes utilisateurs: les vignettes qui expliquent comment utiliser les fonctions du package
- [x] Contenu du Readme
- [x] Documentation {roxygen2} des fonctions
- [x] Messages de commit (de préférence en anglais, par habitude chez nous)
- [x] Description des tests unitaires (de préférence en anglais)
- [x] Code of Conduct: template par défaut de {usethis} en anglais déjà présent comme pour {gouvdown}
- [x] Contributing: template par défaut de {usethis} en anglais peut être ajouté comme pour {gouvdown}

**Comment by jengelaere** [comment]
Tous les utilisateurs, ou mainteneurs futurs seront français... Ils parlent tous français, l'inverse est moins sur. 😃 
Donc français pour tout, sauf pour le code of conduct et le contributing, c'est ok pour rester sur de l'anglais pour eux, car c'est mieux que de ne rien mettre.
Pour les problèmes d'encodage, on peut éviter d'accentuer les caractères qui le nécessiteraient (l'ASCIIfication ne pose pb que pour la doc roxygen a priori), ça restera plus lisible que de l'anglais

**Comment by jengelaere** [comment]
- Rapports d'exploration (présentés en vignettes) : 🇫🇷 
- Vignettes utilisateurs: les vignettes qui expliquent comment utiliser les fonctions du package 🇫🇷 
- Contenu du Readme 🇫🇷 
- Documentation {roxygen2} des fonctions 🇫🇷 
- Messages de commit (de préférence en anglais, par habitude chez nous) 🇫🇷 
- Description des tests unitaires (de préférence en anglais) 🇫🇷 
- Code of Conduct: template par défaut de {usethis} en anglais déjà présent comme pour {gouvdown} 🇬🇧 
- Contributing: template par défaut de {usethis} en anglais peut être ajouté comme pour {gouvdown} 🇬🇧

**Comment by jengelaere** [comment]
je suis en train de me dire que ça ne marche pas avec le template de commit https://github.com/spyrales/shinygouv/blob/9a4b93ba3e326d74c7cd16d6b5852fe23d79ec87/.github/template_commit
je peux le traduire en français au besoin

**Comment by jengelaere** [comment]
Je peux, je crée ma branche à partir de main ?

**Comment by jengelaere** [comment]
c'est bon pour moi
