### ISSUE TITLE
numericInput_dsfr ne fonctionne plus

### ISSUE THREAD

**Issue by arnaud-feldmann** [spyrales/shinygouv#155]
Le shiny numericInput_dsfr ne fonctionne plus avec le shiny actuel (1.8.1.1). Il n'apparait pas parmi les input. Si je rollback en 1.8.0, la classe fonctionne toujours.

**Comment by jengelaere** [comment]
Merci @arnaud-feldmann du signalement, a priori j'ai trouvé d’où vient le soucis, 
peux-tu vérifier en installant 
`devtools::install_github("spyrales/shinygouv", ref =  "155-bug_numericinput_dsfr")`
que c'est réparé ?

**Comment by arnaud-feldmann** [comment]
Salut,
Je confirme que sur mon appli, ton commit fonctionne correctement avec shiny 1.8.1.1.
