### ISSUE TITLE
[CI] déployer automatiquement l'application

### ISSUE THREAD

**Issue by Cervangirard** [spyrales/shinygouv#18]
ETQ dev, je voudrai voir une application qui met en avant l'avancement des composants

## Critère d'acceptation 

- [x] une url avec l'application shiny
> en dev : https://ssm-ecologie.shinyapps.io/shinygouv-demo-dev/
> en prod : https://ssm-ecologie.shinyapps.io/shinygouv-demo/

- [x] un déploiement automatique avec le CI
> voir les fichiers : https://github.com/spyrales/shinygouv/blob/main/.github/workflows/deploy.yaml, https://github.com/spyrales/shinygouv/blob/main/.github/workflows/deploy-dev.yaml et https://github.com/spyrales/shinygouv/blob/main/dev/deploy.R

## Comment technique

- [x] Reprendre le script suivant 
```
rsconnect::setAccountInfo(name   = Sys.getenv("shinyapps_name"),
                          token  = Sys.getenv("shinyapps_token"),
                          secret = Sys.getenv("shinyapps_secret"))

rsconnect::deployApp(appDir = ".",appName = "jeanjean")
```

- [x] Adapter le CI pour l'exécution de ce script

**Comment by Cervangirard** [comment]
@jengelaere , nous sommes bloqué car nous ne pouvons ajouter les var d'env pour le déploiement sur shinyapps.io.
 pourrais-tu ajouter dans la section `Settings > Secrets > Actions` :
![image](https://user-images.githubusercontent.com/37626302/179781641-21ca976d-a6ae-4783-b2d4-5f22e03d2481.png)

Les var d'env suivantes :    

```
SHINYAPPS_NAME=*******
SHINYAPPS_TOKEN=********
SHINYAPPS_SECRET=******
```

Je te remercie

**Comment by jengelaere** [comment]
Bonjour @Cervangirard @MurielleDelmotte , j'ai ajouté les 3 variables d'environnement, sans les ', dites moi si j'aurais du les laisser

**Comment by jengelaere** [comment]
si tu veux, je n'ai pas mis de " ni de '
ça explique peut être ?

**Comment by jengelaere** [comment]
C'est tout bon pour moi, possible d'ajouter le lien vers l'appli demo de dev sur le readme d'accueil du repo ?

**Comment by statnmap** [comment]
On peut voir en local l'app qui est en ligne en faisant `shinygouv::run_app()`
