### ISSUE TITLE
[demo] Intégrer une application Shiny en {shinipsum} avec les composantes {shiny}

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#20]
ETQ utilisateur, je souhaite voir un exemple de comment transformer une application Shiny existante vers le DSFR, afin de pouvoir le reproduire sur mon application

## En attente

- [x] Quelles composantes intégrer pour commencer: https://github.com/spyrales/shinygouv/issues/22

## Critère d'acceptation

- [x] je vois sur la capture d'écran ci-dessous que le package inclut une application Shiny de démonstration contenant les composantes utilisées classiquement, sans DSFR

![image](https://user-images.githubusercontent.com/38312934/183578315-7e714104-28df-426a-a6ba-ca668bf08c71.png)

## Comment technique

- [ ] Créer une base d'app Shiny UI/Server avec modules, qui servira pour la doc et les tests unitaires
- [ ] Y mettre les composantes couramment utilisées listée dans la vignette 

=> Cette application Shiny servira de base pour faire les tests et la documentation de migration d'une app Shiny. Ce n'est pas l'application en démonstration sur Shinyapps.io, mais la base qui servira à la démo en ligne.

**Comment by jengelaere** [comment]
Comment l'utilisateur lance-t-il cette demo ? l'info est peut être quelque part mais j'ai pas vu où

**Comment by jengelaere** [comment]
J'ai lancé un check de {appshinydemo}. Et il ne va pas au bout : 
```
Error: <rlib_error_2_0 in process_get_error_connection(self, private):
 stderr is not a pipe.>
```
En revanche j'arrive à lancer l'application de demo correctement.

**Comment by statnmap** [comment]
Pour faire fonctionner l'app Shiny incluse dans "inst/" pour les dev, il faut lancer:

```
withr::with_dir("inst/appshinydemo/", {
  # oldwd <- setwd()
  pkgload::load_all(export_all = FALSE,helpers = FALSE,attach_testthat = FALSE)
  # options( "golem.app.prod" = TRUE)
  appshinydemo::run_app() # add parameters here (if any)
  # setwd(oldwd)
})
```
