### ISSUE TITLE
[composants] Quelle est la liste des composants à traiter en priorité

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#22]
ETQ dev, je souhaiterai savoir par quels composants je commence à développer

## Problème

Nous avons défini une liste de composants selon ce que nous avons repéré de plus utilisé dans les apps existantes et listé dans ce tableau: https://spyrales.github.io/shinygouv/articles/recommandation-pour-l-implementation-de-dsfr.html#les-inputs-recens%C3%A9s-dans-les-apps-ssm-%C3%A9cologie-par-option

- [x] Sachant les temps de développement estimés dans le tableau, cette liste doit-elle être amendée ? Doit-il y avoir des retraits, une priorisation, des ajouts ?

```
### UI

- fluidPage
- tabPanel
- navbarPage

### UI et interactions server

- actionButton
- selectInput
- sliderInput
- radioButtons
- checkboxGroupInput
- numericInput
- checkBoxinput
- fileInput
- dateRangeInput
- showModal(modalDialog)
- pickerInput
- radioGroupButtons
- materailSwitch
- withSpinner
```

**Comment by jengelaere** [comment]
Bonsoir, je dirais peut être dans cet ordre là :
### UI
- fluidPage
- tabPanel
- navbarPage

### UI et interactions server
- actionButton
- selectInput
- numericInput
- radioButtons
- radioGroupButtons
- checkBoxinput
- checkboxGroupInput
- pickerInput
- sliderInput
- dateRangeInput
- showModal(modalDialog)
- withSpinner
- materailSwitch
- fileInput
- materailSwitch

**Comment by jengelaere** [comment]
En fonction des besoins recensés, notamment ceux de la DRIEAT pour le tableau de bord des mobilités, on échangera surement la fin de la liste avec les élément suivants :

- [ ] dropdown
- [ ] toggle
- [ ] fil vertical
- [ ] accordeon
