### ISSUE TITLE
[composant] Rédiger le guide de développement pour un composant shiny

### ISSUE THREAD

**Issue by Cervangirard** [spyrales/shinygouv#27]
ETQ dev, j'aimerai avoir une procédure à suivre pour savoir comment recoder un composant de dsfr avec une interaction {shiny}, par exempel le `actionButton`

## Critère d'acceptation

- [x] Avoir une documentation dans le dossier dev
<https://github.com/spyrales/shinygouv/blob/main/dev/documentation/comment-faire-un-composant-shiny.md>
- [x] Comprendre l'intérêt des classes déjà existantes dans shiny
<https://github.com/spyrales/shinygouv/blob/main/dev/documentation/comment-faire-un-composant-shiny.md>
- [ ] Etre capable de le refaire soi-même

## Comment technique

- Utilisation des templates html et de la fonction html_template
- Utilisation des classes existantes dans shiny

**Comment by jengelaere** [comment]
Possible de mettre tout les doc flat de dev dans une ou plusieurs vignettes du packages, en indiquant bien qu'elles sont à l'intention des développeurs ? Sinon je ne vois pas bien comment rendre accessible et bien lisible cette info pour un dev à la recherche d'info avant de se lancer et de cloner le repo.

**Comment by jengelaere** [comment]
J'essaie d'intégrer un nouveau composant d'ici à mercredi avant de cocher la 3e case.

**Comment by jengelaere** [comment]
Quel est le fichier à maintenir entre :  
- https://github.com/spyrales/shinygouv/blob/main/dev/documentation/comment-faire-un-composant-shiny.Rmd  
- https://github.com/spyrales/shinygouv/blob/main/dev/flat_comment-faire-un-composant-shiny.Rmd

**Comment by statnmap** [comment]
Il faudrait ajouter dans le guide de dev, des infos sur les pré-requis: guide et pages aweb existantes:
- doc de fusen
- JS pour R users
- C'est quoi un HTML / CSS / JS
- C'est quoi un package R
