### ISSUE TITLE
[composant] création du composant radiobutton

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#29]
ETQ dev, j'aimerai suivre la procédure "comment recoder un composant de dsfr avec une interaction {shiny}", pour coder le radioButton

## Critère d'acceptation

- [x] une fonction implementée, documentée, testée : `radioButton_dsfr()' 
      - voir doc : <https://github.com/spyrales/shinygouv/blob/main/dev/documentation/radiobuttons_dsfr.Rmd>
      
![image](https://user-images.githubusercontent.com/37626302/183894366-68317566-f728-4ab9-88cb-3cca51beb58c.png)

## Comment technique

- Utilisation du workflow 'dev/documentation/comment-faire-un-composant-shiny.Rmd'

**Comment by jdlom** [comment]
Je viens de regarder le code et je me demandais  pourquoi vous n'aviez pas repris l'argument **_selected_**  pour préselectionner éventuellement une valeur ? Il y a peut-être quelque chose qui m'échappe.

**Comment by statnmap** [comment]
Bonne remarque. C'est parce que nous nous sommes concentrés par l'élaboration du processus de développement des composants, et les tests de ce processus, avant de se pencher réellement sur les différents paramètres disponibles dans les fonctions Shiny, à ré-implémenter dans les fonctions du dsfr.  
J'ouvre une issue à ce sujet: https://github.com/spyrales/shinygouv/issues/53

**Comment by jengelaere** [comment]
Validé
