### ISSUE TITLE
[orga] Défintion des rôles

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#3]
ETQ LeadDev, j'ai besoin de savoir qui est responsable de quoi sur ce projet, afin de savoir vers qui me tourner si j'ai des questions, des tickets à valider ou des priorisations à réaliser

## Critères d'acceptation

> ThinkR s'occupe de la mise en place du projet, des explorations du DSE en lien avec Shiny et des premiers développements. 

- [x] Je connais les personnes référentes pour les décisions d'orientation du projet: Juliette Engelaere-Lefebvre 
- [x] Je connais les personnes référentes côté ThinkR pour la gestion du projet: Sébastien Rochette, Margot Brard
- [x] Je connais les développeurs côté ThinkR: Murielle Delmotte, Cervan Girard
- [x] Je connais les personnes qui peuvent valider les livrables: Juliette Engelaere-Lefebvre, ...
- [x] Je connais les personnes qui peuvent reprendre la maintenance du projet à l'issue de la mission ThinkR: Juliette Engelaere-Lefebvre , ...

**Comment by jdlom** [comment]
Juste pour confirmer mon intérêt
