### ISSUE TITLE
[layout] Implementer fuildpage

### ISSUE THREAD

**Issue by Cervangirard** [spyrales/shinygouv#30]
ETQ dev, je veux pouvoir initier une nouvelle application avec fluiPage_dsfr ou navbarPage_dsfr

## Critère d'acceptation 

- [x] une fonction pour fluidpage
![image](https://user-images.githubusercontent.com/37626302/183893425-d49e5d0b-c414-475f-9a6b-f3f49cd6241d.png)

Disponible sur l'url : <https://ssm-ecologie.shinyapps.io/shinygouv-demo/>

## Comment 

- ajouter les dépendances
- gérer le javascript

**Comment by jengelaere** [comment]
Fonction incomplète ?
https://github.com/spyrales/shinygouv/blob/main/R/fluidpage_dsfr.R
# TODO theme et lang
# check les params

**Comment by statnmap** [comment]
Retirer les paramètres supp non implémentés. Et attendre de voir si c'est nécessaire.
