### ISSUE TITLE
[meta] Priorisation des développements

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#31]
ETQ LeadDev, je souhaite prioriser les tâches de développement afin que la reprise et l'adoption du package se fassent dans les meilleures conditions

## Problèmes

Etant donné le temps imparti pour la mission, il faut choisir entre l'implémentation de nouvelles fonctionnalités, et le guide de développement pour une bonne prise en main des développeurs et utilisateurs.

Il y a plusieurs choses à traiter. Voici le choix de priorisation que nous avons fait:  

1. Expliquer aux développeuses et développeurs du package comment ajouter une nouvelle composante et comment la documenter. Sachant qu'il y a des composantes plus complexes que d'autres. Exemples avec `fluidPage()`, `actionButton()` et `radioButton()`.
2. Expliquer aux utilisatrices et utilisateurs de {shinygouv} comment transformer leurs applications Shiny existantes pour qu'elles utilisent le DSFR. Exemple avec l'application Shiny de démonstration du package {shinygouv}.
3. Expliquer aux utilisatrices et utilisateurs de {shinygouv} comment créer une application Shiny depuis une page blanche en utilisant le DSFR directement. Documentation des composantes incluses et de leur utilisation.
4. Indiquer ce qui est possible ou non avec les composantes du DSFR, avec la liste des composantes déjà incluses
5. Inclure les autres composantes

## Validation

- [x] @jengelaere peux-tu nous confirmer que l'aide au développement et à l'utilisation est plus important que d'ajouter le plus possible de composantes dans le package ?

Note qu'il est peu probable que nous n'irons pas beaucoup plus loin que ces 3 composantes: `fluidPage()`, `actionButton()` et `radioButton()`. Mais une fois que tous les templates et doc seront prêts, ça ira beaucoup plus vite pour vous.

**Comment by jengelaere** [comment]
C'est bon pour moi

**Comment by jengelaere** [comment]
Dans l'aide à l'utilisation, il faudrait peut être que la doc d'un composant renvoie vers l'ide de la fonction shiny transposée ?
