### ISSUE TITLE
[Documentation] Rédiger le guide de transformation d'un app shiny vers une app shiny dsfr

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#33]
ETQ utilisateur/utilisatrice je veux savoir comment transformer mon application Shiny existante pour qu'elle utilise le DSFR

## Critère d'acceptation

- [x] Avoir une vignette qui documente la procédure de transformation

https://spyrales.github.io/shinygouv/articles/convertir-une-app-shiny-en-app-shiny-dsfr.html

- [x] Avoir une fonction qui permet de convertir une application shiny en application shiny dsfr

![image](https://user-images.githubusercontent.com/38312934/183933279-e08459cd-015a-4f4d-9420-03c0c8fd892b.png)

- [ ] Etre capable de le refaire soi-même

- [x] utilisation de la fonction sur l'application de demo: (disponible dans 'inst\appshinydemo')
![image](https://user-images.githubusercontent.com/38312934/184095792-96238e51-f681-470c-a070-49d5ea317996.png)

Après passage de `convert_to_dsfr(version = "1.7.2")`
![image](https://user-images.githubusercontent.com/38312934/184095433-48d39aee-73cf-43d2-a429-5ddda566aad8.png)

## Comment technique

- Création d'un tableur csv dans inst/vx.y.z qui reprendre les composants déjà implementer et leur correspondance (shiny <-> dsfr)
- Créer une fonction qui remplace toutes les composantes shiny en dsfr (quand elles ont été implémentée)
- faire le test sur l'appshinydemo

**Comment by jengelaere** [comment]
ça a l'air top cette fonction ! J'ai hâte de pouvoir la tester

**Comment by jengelaere** [comment]
J'ai testé sur une appli basique  type 'Old Faithful Geyser Data', c'est un peu maximaliste dans ce cas ! J'ai des `header_dsfr(` avant chaque `(`
En revanche top pour la golem de demo.

**Comment by jengelaere** [comment]
Validé !
