### ISSUE TITLE
[composant] implémentation du header

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#35]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un header conforme au dsfr à mon application shiny dsfr

## Critère d'acceptation

- [x] une fonction implementée, documentée, testée : `header_dsfr()' 

![image](https://user-images.githubusercontent.com/38312934/183900364-cd9cb21d-2625-43e9-a9c1-b18c468f35dc.png)

- [x] Exemple d'utilisation dans l'application de demo

https://ssm-ecologie.shinyapps.io/shinygouv-demo/

## Comment technique

- Utilisation du workflow 'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Modifier le fluidPage_dsfr pour qu'il prenne, si nécessaire, le header

**Comment by jengelaere** [comment]
TODO verifier que l url est valide ?  
https://github.com/spyrales/shinygouv/blob/main/R/header_dsfr.R#L34

**Comment by jengelaere** [comment]
On peut supprimer https://github.com/spyrales/shinygouv/blob/main/dev/documentation/header_dsfr.Rmd ?

**Comment by statnmap** [comment]
Un TODO a nettoyer.  
Le reste inclu dans le #58
