### ISSUE TITLE
[Documentation] Rédiger le guide de creation d'une nouvelle app shiny dsfr

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#36]
ETQ utilisateur/utilisatrice je veux savoir comment créer une nouvelle application Shiny utilisant le DSFR

## Critère d'acceptation

- [x] Avoir une vignette qui documente la procédure de création d'une nouvelle app shiny dsfr: https://spyrales.github.io/shinygouv/articles/comment-demarrer-une-nouvelle-application-shiny-dsfr.html  
![image](https://user-images.githubusercontent.com/38312934/184127251-f2571378-1d18-4da9-b940-10d06a321c06.png)

## Comment technique

- [ ] nouveau flat indiquant la création d'un golem + convert_to_dsfr()
- [ ] y faire référence à la table des composants déjà implémentés ainsi que la documentation
- [ ] référence au DSFR pour les règles d'usage

**Comment by jengelaere** [comment]
Validé !
