### ISSUE TITLE
[layout] implementer la fonction navbarPage

### ISSUE THREAD

**Issue by Cervangirard** [spyrales/shinygouv#37]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `navbarPage()` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [ ] Une fonction implementée, documentée, testée : `navbarPage_dsfr()'
   - [ ] Avec la documentation dans le corps de la fonction
   - [ ] La présentation dans une vignette
   - [ ] Des tests unitaires
- [ ] Un exemple d'utilisation dans l'application de démonstration est disponible

## Comment technique

- Je crée une branche pour développer la fonctionnalité
- Utilisation du workflow décrit dans  'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Utiliser le flat file fourni pour développer avec {fusen}
- J'ouvre une PR assignée aux responsables de projet lorsque c'est traité

**Comment by jengelaere** [comment]
@Cervangirard @MurielleDelmotte 
j'essaie le process avec navbarPage 😨 je pensais que ce serait assez simple, je crois que je me suis trompée...
il l'a faut associer aux onglets dsfr https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/onglets + fluidpage + header ?

**Comment by jengelaere** [comment]
c'est surement plutôt 
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/navigation-principale

**Comment by statnmap** [comment]
Explorer d'abord #59 avant de se lancer ici.

**Comment by ColinFay** [comment]
Supplémenté par #73
