### ISSUE TITLE
[doc] Mettre à jour le README du developpeur

### ISSUE THREAD

**Issue by Cervangirard** [spyrales/shinygouv#39]
ETQ dev, je veux une page qui explique ou se situe les fichiers

## Acceptation

- [ ] des liens vers les différents md pour le développement

![image](https://user-images.githubusercontent.com/37626302/183893210-0565c159-3a42-41b7-b4e9-4303b8f42a39.png)

- [x]  Le readme indique comment créer une issue et une branche

![image](https://user-images.githubusercontent.com/21193866/183943105-d1d8320b-6157-44e5-aef7-b8e97adaf8af.png)

- [x] Il y a un template d'issue pour l'ajout de nouveau composant
![image](https://user-images.githubusercontent.com/21193866/183943225-085b02ff-0675-4927-bbbb-6a53436952fd.png)

## Comment

Reprendre le dossier documentation et le structure. Ajotuer les liens dans le README

**Comment by jengelaere** [comment]
Les liens 

> [Comment faire un composant shiny](https://github.com/spyrales/shinygouv/blob/main/dev/documentation/comment-faire-un-composant-shiny.md)
> 
> Vous trouverez des exemples pour d’autres composants :
> 
>     Avec réactivité:
>         [radio buttons](https://github.com/spyrales/shinygouv/blob/main/dev/documentation/radiobuttons-dsfr.md)
>     Sans réactivité:
>         [Fluid page](https://github.com/spyrales/shinygouv/blob/main/dev/documentation/fluidpage_dsfr.md)

sont cassés.

Doc à passer en vignette ou dans le wiki du repo ?

**Comment by jengelaere** [comment]
La présentation du concept choisi (l'option D) devrait figurer dans ce readme
