### ISSUE TITLE
[explo-terrain] Inventaire des templates et composantes des applications Shiny déjà développées

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#4]
ETQ dev je souhaite connaître la liste des templates et composantes des app Shiny déjà déployées, afin d'orienter mes choix de développements vers des changements d'usages les plus réduits possibles

## Critères d'acceptation

- [x] Un accès à la liste d'application existantes est disponible: Murielle et Juliette y ont accès
- [x] Un rapport (sous forme de vignette du package) fait l'état des lieux des templates utilisés: https://spyrales.github.io/shinygouv/articles/documentation-inventaire.html
![image](https://user-images.githubusercontent.com/21193866/179506913-1f6ae85a-73cb-4759-ae97-876deab84543.png)

- [x] Le rapport fait état des composantes shiny les plus utilisées: https://spyrales.github.io/shinygouv/articles/documentation-inventaire.html#les-composantes
![image](https://user-images.githubusercontent.com/21193866/179506945-c28886d3-d606-4c7c-95f9-2f70cd22be12.png)

## Comment technique

- [x] Créer une vignette dans le package pour lister les observations
- [x] Dans la liste d'app, présenter les outils de mise en page des apps: `bootstrapPage`,  `fluidPage`,  `navbarPage`,  `tabPanel`, `shinydashboard`, ...
- [x] Recenser de manière qualitative les composantes de {shiny} les plus utilisées pour l'interactivité : `actionButton`, `modalDialog`, `selectInput`, ...
    - [x] Les noter de telle sorte qu'on puisse récupérer cette liste facilement pour mettre dans l'application de démo
- [x] Recenser les composantes hors {shiny} les plus utilisées : {shinyWidgets}, {bsplus}, {leaflet}, ...

**Comment by jengelaere** [comment]
top !
