### ISSUE TITLE
[composant] Implémentation de `checkBoxInput()`

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#42]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `checkBoxInput()` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [ ] Une fonction implementée, documentée, testée : `checkBoxInput_dsfr()'
   - [ ] Avec la documentation dans le corps de la fonction
   - [ ] La présentation dans une vignette
   - [ ] Des tests unitaires
- [ ] Un exemple d'utilisation dans l'application de démonstration est disponible

## Comment technique

- Je crée une branche pour développer la fonctionnalité
- Utilisation du workflow décrit dans  'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Utiliser le flat file fourni pour développer avec {fusen}
- J'ouvre une PR assignée à @statnmap lorsque c'est traité

**Comment by Cervangirard** [comment]
Merci pour le travail. nous nous en sommes inspiré <3
