### ISSUE TITLE
[Documentation] Completer les tests unitaires et la procédure

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#50]
ETQ developpeur, je suis alerté si des changements n'ont pas été pris en compte à la nouvelle version du dsfr.

## Critère d'acceptation
- [x] les fonctions des composants sont testées avec leurs paramètres d'entrée, et le HTML de sortie
   - [x] Exemple pour radioButtion

![image](https://user-images.githubusercontent.com/21193866/185575583-d87f91bb-6ed6-479c-81c8-02700608327c.png)
![image](https://user-images.githubusercontent.com/21193866/185575648-63a327ab-bdd1-4a38-b668-20ffebc2d82b.png)

- [x] la procédure est complétée
![image](https://user-images.githubusercontent.com/38312934/184331490-7d7ff041-69ba-4ae1-9d22-6573f0f6ffbb.png)

## Critère technique
- Ajout de tests unitaires pour chaque composant
- Procédure à revoir

**Comment by jengelaere** [comment]
Ajouter les liens vers flat_new_one.Rmd et vers et vers exemple dev/flat_composants/flat_actionButton.Rmd (sur repo github ?)

**Comment by Cervangirard** [comment]
@MurielleDelmotte si tu veux bien repasser sur les vingettes pour les liens, merci ^^

**Comment by MurielleDelmotte** [comment]
@jengelaere 
Les liens/url ont été ajoutés
je te laisse valider et fermer cette issue si cela te convient.

**Comment by jengelaere** [comment]
👌
