### ISSUE TITLE
[Documentation] Probleme de prise en compte des NA dans convert_to_dsfr

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#56]
ETQ utilisateurs, la fonction convert_to_dsfr ne doit pas remplacer tous les `(` par `header_dsfr(`

# Critère d'acceptation
- [x] Une conversion d'une appli basique type 'Old Faithful Geyser Data' réussie. c'est à dire que seul les composants ayant un équivalent shiny <> dsfr sont remplacés.

![image](https://user-images.githubusercontent.com/38312934/188410095-93f3552e-7d09-4822-a70d-f5cc3db6dc7d.png)

Après conversion: 

![image](https://user-images.githubusercontent.com/38312934/188410386-573c4f91-8f85-4081-aebe-0fb0d6d4a166.png)

# Critère techniques
- [x] rajouter na.string=c("","NA") dans la lecture de la table de correspondance.
- [x] ajouter un test unitaire

**Comment by jengelaere** [comment]
Validé !
