### ISSUE TITLE
Restructurer dev et le mode de développement

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#58]
ETQ dev, j'aimerai avoir un accès clair à la doc de dev, pour savior si je m'implique ou pas, et comment ça va se passer.

## acceptation

- [ ] Je sais ou trouver le doc de développeur pour la mise en place
- [ ] Je sais ou trouver le doc de développeur pour la création d'un nouveau template
- [ ] Je sais ou trouver le template_flat_new_one pour démarrer mon développement
- [ ] Contributing => Je sais comment réformer un flat_file (c'est écrit que je ne doit plus le modifier...)
- [ ] Contributing => Je sais comment maintenir les fonctions existantes

## comment technique

- On utiliser le flat template pour la creation d'un nouveau composant
- Quand le composant est fini en première version fonctionnelle, on réforme le flat_template dans "dev/dev_history"
- Le flat template dun composant ne produit pas de vignette (ce qui va alléger le dossier dev/documentation)
- Le dossier dev/documentation est supprimé
- flat_new_one.Rmd => template_flat_new_one.Rmd, à mettre à la racine de dev
- Comment creer un composant, est plutôt une vignette de dev, nommé "dev - ", Réservée aux dev
- Le Readme de dev/documentation est mis en vignette de "dev-"

**Comment by Cervangirard** [comment]
Je ferme car réouverture de l'issue #109
