### ISSUE TITLE
[composant] Implémentation de selectInput

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#59]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `selectInput()` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [ ] Une fonction implementée, documentée, testée : `selectInput_dsfr()'
   - [ ] Avec la documentation dans le corps de la fonction
   - [ ] La présentation dans une vignette
   - [ ] Des tests unitaires
- [ ] Un exemple d'utilisation dans l'application de démonstration est disponible

## Comment technique

- Je crée une branche pour développer la fonctionnalité
- Utilisation du workflow décrit dans  'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Utiliser le flat file fourni pour développer avec {fusen}
- J'ouvre une PR assignée aux responsables de projet lorsque c'est traité

**Comment by jengelaere** [comment]
Doublon #80
