### ISSUE TITLE
[connaissance-DSE] Définir où sont les fichiers web sources et comment les récupérer lors des mises à jour

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#6]
ETQ dev, j'ai besoin de savoir quel fichiers de configuration je peux utiliser comme source pour le développement du package, afin de pouvoir mettre à jour son contenu en lien avec le DSE

## Critères de validation

- [x] Je sais où sont stockés les éventuels fichiers CSS / JS du DSE 
      - Ils sont maintenant stockés dans "inst/dsfr-v1.6.0" pour la dernière version: https://github.com/spyrales/shinygouv/tree/main/inst/dsfr-v1.6.0/dist
![image](https://user-images.githubusercontent.com/21193866/179536299-b10769f9-225a-40c4-92dc-f406114a0f28.png)

- [x] Je sais comment je peux les récupérer manuellement ou automatiquement
      - Une vignette a été rédigée en ce sens pour clarifier comment télécharger et quels fichiers garder: https://spyrales.github.io/shinygouv/articles/trouver_css_js.html  
![image](https://user-images.githubusercontent.com/21193866/179536026-1114bc8c-592a-49ad-a051-17eb35060f7c.png)

## Comment technique

- Le site du DES est : https://gouvfr.atlassian.net/wiki/spaces/DB/pages/193003540/COMMENT+UTILISER+LE+DSFR

**Comment by jengelaere** [comment]
👍
