### ISSUE TITLE
[deliverables] Livraison de la version 0.0.1

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#60]
ETQ client, je souhaite avoir accès aux différents rapports de qualité de la livraison

## Critères d'acceptation

- [x] J'ai récupéré un dossier de livrables: [deliverables.zip](https://github.com/spyrales/shinygouv/files/9507321/deliverables.zip)
- [x] Le livrable contient le rapport de couverture de code (codecoverage) + l'explication des indicateurs
- [x] Le livrable contient le rapport des messages de commit associés au issues GitHub (gitdown)
- [x] Le livrable contient le rapport de tests unitaires par fichier de test (testdown)
- [x] Le résumé du code coverage est dans une vignette: https://spyrales.github.io/shinygouv/articles/tests_and_coverage.html
- [x] La version du dépôt git est taguée `v0.0.1`: https://github.com/spyrales/shinygouv/releases/tag/v0.0.1

## Comment technique

- Executer le code dans "dev/dev_history_deliverables.R"

**Comment by jengelaere** [comment]
C'est top !
