### ISSUE TITLE
[bug] Encodages des paramètres

### ISSUE THREAD

**Issue by jengelaere** [spyrales/shinygouv#62]
## Validation 

+ [x] L'app déployée sur https://ssm-ecologie.shinyapps.io/shinygouv-demo/ possède des caractères spéciaux 
  - Dans le header
  - Dans les boutons

![Screenshot 2023-06-27 at 09 43 52](https://github.com/spyrales/shinygouv/assets/17936236/0bc975f2-f7fe-4a66-80e6-e7f1d320ad19)

## Dev

ETQ utilisateur windows de la fonction header_dsfr(), je ne sais pas comment ajouter un "é" dans "préfet" au niveau du paramètre `intitule` pour que l'encodage soit traité correctement

![image](https://github.com/spyrales/shinygouv/assets/37416795/9ca602a5-dae1-4aef-b8c6-5a97d40c2218)

**Comment by ColinFay** [comment]
Fermé par erreur, je réouvre :)

**Comment by ColinFay** [comment]
@jengelaere à valider :)

**Comment by jengelaere** [comment]
c'est testé, validé et approuvé, merci ! Je ferme ?

**Comment by ColinFay** [comment]
@jengelaere Oui tu peux fermer les prochaines :) 

Je m'occupe de celle ci :)
