### ISSUE TITLE
[composant] Implémentation de navbarPage 

### ISSUE THREAD

**Issue by ColinFay** [spyrales/shinygouv#73]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `navbarPage_dsfr` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [x] Une fonction implementée, documentée, testée : `navbarPage_dsfr()'
   - [x] Avec la documentation dans le corps de la fonction https://github.com/spyrales/shinygouv/blob/main/R/navbarpage_dsfr.R#L98
   - [x] Des tests unitaires https://github.com/spyrales/shinygouv/blob/main/tests/testthat/test-navbarpage_dsfr.R 
- [x] Un exemple d'utilisation dans l'application de démonstration est disponible https://ssm-ecologie.shinyapps.io/shinygouv-demo/
	- [x] La fonctionnalité de navbar est fonctionnelle : quand je clique sur un onglet, le contenu change et la réactivité fonctionne
	- [x] Je peux pointer vers un onglet avec l'url : https://ssm-ecologie.shinyapps.io/shinygouv-demo/#with_spinner_dsfr

**Comment by ColinFay** [comment]
pour validation @jengelaere

**Comment by jengelaere** [comment]
manque juste dans le news.md

**Comment by Cervangirard** [comment]
merci, je ferme et on ouvre une issue pour le new.md
