### ISSUE TITLE
[composant] Implémentation de withSpinner

### ISSUE THREAD

**Issue by ColinFay** [spyrales/shinygouv#74]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `[COMPOSANT]()` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [x] Une fonction implementée, documentée, testée : `[COMPOSANT]_dsfr()'
   - [x] Avec la documentation dans le corps de la fonction

![image](https://github.com/spyrales/shinygouv/assets/49268931/ddc010dd-e1ba-4e60-8949-bfc6eee40e61)

   - [x] La présentation dans une vignette

![image](https://github.com/spyrales/shinygouv/assets/49268931/974f0708-1ae5-4946-98ee-9197adf94849)

   - [x] Des tests unitaires

-> Développements à prévoir. Il s'agit d'un cas particulier pour lequel nous n'avons pas encore la méthodologie sous la main pour le tester

- [x] Un exemple d'utilisation dans l'application de démonstration est disponible

https://ssm-ecologie.shinyapps.io/shinygouv-demo/# 

-> onglet withSpinner_dsfr

## Comment technique

- Je crée une branche pour développer la fonctionnalité
- Utilisation du workflow décrit dans  'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Utiliser le flat file fourni pour développer avec {fusen}
- J'ouvre une PR assignée aux responsables de projet lorsque c'est traité

Pseudo code : 

```
with_spinner <- \(expr, session = shiny::getDefaultReactiveDomain()){
  showSpinner(session = session)
  force(expr)
  on.exit(hideSpinner(session = session))
}
# s'inspirer de shiny::withProgress
# Prendre un css de https://loading.io/css/
```
Mettre en hidden par défaut
Position du div est fixe et mettre au milieu de la page 
https://colinfay.me/watch-r-shiny/

En fait le spinner est tout le temps là
showSpinner : affiche
hideSpinner : cache

**Comment by jengelaere** [comment]
Pareil que pour le selectInput, pour moi tout ok sur le fonctionnement (pas très grave pour le test manquant) juste des § en trop sur la vignette, j'imagine qu'on évoquera ça globalement lundi AM avec @Cervangirard quand on parlera restructuration de la doc ?
