### ISSUE TITLE
[composant] Implémentation de selectInput()

### ISSUE THREAD

**Issue by ymansiaux** [spyrales/shinygouv#80]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `selectInput()` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [x] Une fonction implementée, documentée, testée : `selectInput_dsfr()'
   - [x] Avec la documentation dans le corps de la fonction

![image](https://github.com/spyrales/shinygouv/assets/49268931/4fc814ad-5a33-4945-bac1-1f766551d8b3)  

   - [x] La présentation dans une vignette

![image](https://github.com/spyrales/shinygouv/assets/49268931/cc6501de-5ec6-4ce5-808c-056a06e74340)

   - [x] Des tests unitaires

![image](https://github.com/spyrales/shinygouv/assets/49268931/a26ab8ac-77ae-4db7-8155-8a16ee88e36e)

- [x] Un exemple d'utilisation dans l'application de démonstration est disponible

https://ssm-ecologie.shinyapps.io/shinygouv-demo/#

-> onglet selectInput_dsfr

## Comment technique

- Je crée une branche pour développer la fonctionnalité
- Utilisation du workflow décrit dans  'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Utiliser le flat file fourni pour développer avec {fusen}
- J'ouvre une PR assignée aux responsables de projet lorsque c'est traité

**Comment by jengelaere** [comment]
Sur la vignette, on peut enlever les § vides ?

> # selectInput_options_dsfr_template
> 
> # selectInput_dsfr_template

**Comment by jengelaere** [comment]
Je chipote car, tout marche bien 😄 
Juste faut que je me replonge dans fusen pour retrouver pourquoi on a des parties vides dans la vignette

**Comment by ymansiaux** [comment]
Bonjour

Je vais aussi investiguer ces paragraphes vides. Si pas possible de les enlever, j'ajouterai un petit texte pour dire qu'il s'agit de fonctions internes utilisées par l'input en question (c'est + pertinent pour un développeur que pour un utilisateur ceci dit ...)

**Comment by Cervangirard** [comment]
Je me permets de fermer et de reparler des vignettes lundi
