### ISSUE TITLE
[switch] Implémentation de [switch]

### ISSUE THREAD

**Issue by Cervangirard** [spyrales/shinygouv#81]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type switch conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [x] Une fonction implementée, documentée, testée : `switch_dsfr()'
- [x] Un exemple d'utilisation dans l'application de démonstration est disponible

https://ssm-ecologie.shinyapps.io/shinygouv-demo/
voir section toggleSwitch_dsfr

## Comment technique

- Je crée une branche pour développer la fonctionnalité
- Utilisation du workflow décrit dans  'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Utiliser le flat file fourni pour développer avec {fusen}
- J'ouvre une PR assignée aux responsables de projet lorsque c'est traité

**Comment by jengelaere** [comment]
Elle est vraiment dans la démo ? pas vue ? En tout cas elle marche bien et la doc est ok

**Comment by Cervangirard** [comment]
on l'ajoute, merci et dsl de l'oubli
