### ISSUE TITLE
[rework] retour client

### ISSUE THREAD

**Issue by Cervangirard** [spyrales/shinygouv#88]
Ticket ouvert suite aux retours de @jengelaere le 28/06/2023

## Validation

- [x] toggleSwitch_dsfr a été ajouté dans l'app de démo

https://ssm-ecologie.shinyapps.io/shinygouv-demo/
voir section toggleSwitch_dsfr

- [x] le news a été incrémenté avec les nouvelles fonctionnalités
       - [ ] un commit propre d'implem d'un composant est cité

https://github.com/spyrales/shinygouv/blob/main/NEWS.md

![image](https://github.com/spyrales/shinygouv/assets/49268931/25ebeca8-984c-4d6c-9a5f-028dad6c5280)

- [x] les branches mergées ont été supprimées
- [ ] 
https://github.com/spyrales/shinygouv/branches

## Dev 

- [x] toggleSwitch_dsfr a été ajouté dans l'app de démo
- [x] le news a été incrémenté avec les nouvelles fonctionnalités
       - [ ] un commit propre d'implem d'un composant est cité
- [x] supprimer les branches mergées

**Comment by jengelaere** [comment]
✔️
