### ISSUE TITLE
[composant] Implémentation de checkBoxInput()

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#89]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `checkBoxInput()` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [x] Une fonction implementée, documentée, testée : `checkBoxInput_dsfr()'
   - [x] Avec la documentation dans le corps de la fonction

![image](https://github.com/spyrales/shinygouv/assets/38312934/4f4c0e6c-799c-4258-a9bb-f035b513be5c)

   - [x] Des tests unitaires

![image](https://github.com/spyrales/shinygouv/assets/38312934/1d2fd4d8-946d-4ee7-acce-a189b60b743b)

- [x] Un exemple d'utilisation dans l'application de démonstration est disponible

https://ssm-ecologie.shinyapps.io/shinygouv-demo/#

## Comment technique

- Je crée une branche pour développer la fonctionnalité
- Utilisation du workflow décrit dans  'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Utiliser le flat file fourni pour développer avec {fusen}
- J'ouvre une PR assignée aux responsables de projet lorsque c'est traité

**Comment by jengelaere** [comment]
✔️ top
