### ISSUE TITLE
[composant] Implémentation de numericInput()

### ISSUE THREAD

**Issue by ymansiaux** [spyrales/shinygouv#92]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `numericInput()` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [x] Une fonction implementée, documentée, testée : `numericInput_dsfr()'
   - [x] Avec la documentation dans le corps de la fonction

![image](https://github.com/spyrales/shinygouv/assets/49268931/7eba6599-932c-44e0-8967-a288f147276a)

   - [x] Des tests unitaires
  
![image](https://github.com/spyrales/shinygouv/assets/49268931/e18dee75-d921-48f5-80d4-9e65c4f74eee)

- [x] Un exemple d'utilisation dans l'application de démonstration est disponible

https://ssm-ecologie.shinyapps.io/shinygouv-demo/#numeric_input_dsfr

-> section numericInput_dsfr

## Comment technique

- Je crée une branche pour développer la fonctionnalité
- Utilisation du workflow décrit dans  'dev/documentation/comment-faire-un-composant-shiny.Rmd'
- Utiliser le flat file fourni pour développer avec {fusen}
- J'ouvre une PR assignée aux responsables de projet lorsque c'est traité

**Comment by jengelaere** [comment]
tout ok, juste manque la mention dans le news.md

**Comment by Cervangirard** [comment]
on ouvre une issue pour le new
