### ISSUE TITLE
feat: tabPanel

### ISSUE THREAD

**Issue by ColinFay** [spyrales/shinygouv#97]
## Validation 

+ [x] J'ai accès au tabPanel sur l'appli de démo 

https://ssm-ecologie.shinyapps.io/shinygouv-demo/

+ [x] L'UI est iso avec le DSFR

dsfr :

![image](https://github.com/spyrales/shinygouv/assets/49268931/b6f738ea-28a6-4437-9ea3-2db7535dac0a)

shiny:

![image](https://github.com/spyrales/shinygouv/assets/49268931/3ac527c4-2882-4902-9f3e-d7861f591852)

+ [x] La fonction possède un exemple 

![image](https://github.com/spyrales/shinygouv/assets/49268931/93689d65-6970-416d-9113-e09e77f1f79f)

+ [x] La fonction est testées

![image](https://github.com/spyrales/shinygouv/assets/49268931/1d6ecc2b-d1e6-4292-9342-5710bb6b1b41)

**Comment by jengelaere** [comment]
👌
