### ISSUE TITLE
[composant] Implémentation de checkBoxgroupInput_dsfr()

### ISSUE THREAD

**Issue by MurielleDelmotte** [spyrales/shinygouv#98]
ETQ utilisateur/utilisatrice, je souhaite pouvoir ajouter un composant de type `checkBoxgroupInput_dsfr()` conforme au dsfr à mon application shiny dsfr

## Critères d'acceptation des développements effectués

- [x] Une fonction implementée, documentée, testée : `checkBoxgroupInput_dsfr()'
   - [x] Avec la documentation dans le corps de la fonction
![image](https://github.com/spyrales/shinygouv/assets/37626302/86e5f977-b099-4117-a3d2-7ac2ceff70b6)

   - [x] Des tests unitaires

![image](https://github.com/spyrales/shinygouv/assets/37626302/279ce154-ca1d-4b1d-b7c6-0f295e1ac08b)

- [x] Un exemple d'utilisation dans l'application de démonstration est disponible

https://ssm-ecologie.shinyapps.io/shinygouv-demo/#

**Comment by jengelaere** [comment]
Tout ok, faudra juste penser à implémenter dans le news.md

**Comment by jengelaere** [comment]
👌
